services:
  django: &django
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  redis-qoovee:
    image: redis:6.0.9
    restart: always
    ports:
      - "6379:6379"

  redis-messanger:
    image: redis:6.0.9
    restart: always
    ports:
      - "6380:6380"

  celery-worker:
    build: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker -n yatsworker --loglevel=info
    volumes:
      - .:/usr/src/app
    links:
      - redis-qoovee
    depends_on:
      - redis-qoovee
      - pgdb

  flower:
    build: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - .:/usr/src/app
    links:
      - redis-qoovee
    depends_on:
      - redis-qoovee
      - pgdb
    ports:
      - "5555:5555"

volumes:
  pgdbdata: null