version: '3.9'

networks:
  default:
    driver: bridge

services:
  django:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    entrypoint: redis-server --appendonly yes --requirepass somepass --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - default
    ports:
      - "6379:6379"
    volumes:
      - /var/lib/appdata/redis/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  pgdbdata: null